export default function getAllProducts() {
  return [
    {
      id: '911-gt3-1',
      slug: 'porsche-911-gt3',
      name: 'Porsche 911 GT3',
      category: 'Sports Cars',
      categorySlug: '911',
      price: 3_000_000_000,
      stock: 5,
      imageUrl: '/assets/images/mobil1.jpg', // Kiri atas
      description: 'The Porsche 911 GT3 offers track-ready performance and iconic design.',
    },
    {
      id: '718-carrera-red',
      slug: 'porsche-718-carrera-red',
      name: 'Porsche 718 Carrera Red',
      category: 'Sports Cars',
      categorySlug: '718',
      price: 2_900_000_000,
      stock: 3,
      imageUrl: '/assets/images/mobil2.jpg',
      description: 'Experience the power and beauty of the Porsche 718 Carrera in red.',
    },
    {
      id: '911-gt3-pink',
      slug: 'porsche-911-gt3-pinl',
      name: 'Porsche 911 GT3 Grey',
      category: 'Sports Cars',
      categorySlug: '911',
      price: 3_100_000_000,
      stock: 0,
      imageUrl: '/assets/images/mobil3.jpg', // Out of Stock
      description: 'A rare edition of the Porsche 911 GT3 in grey, perfect for enthusiasts.',
    },
    {
      id: '718-cabriolet-blue',
      slug: 'porsche-718-cabriolet-blue',
      name: 'Porsche 718 Cabriolet Blue',
      category: 'Sports Cars',
      categorySlug: '718',
      price: 2_700_000_000,
      stock: 4,
      imageUrl: '/assets/images/mobil4.jpg',
      description: 'Open-air luxury with the Porsche 718 Cabriolet in blue.',
    },
    {
      id: '911-gt3-black',
      slug: 'porsche-911-gt3-black',
      name: 'Porsche 911 GT3 Black',
      category: 'Sports Cars',
      categorySlug: '911',
      price: 3_200_000_000,
      stock: 6,
      imageUrl: '/assets/images/mobil5.jpg',
      description: 'The Porsche 911 GT3 in black delivers bold performance and aesthetics.',
    },
    {
      id: 'classic-993-silver',
      slug: 'classic-porsche-993-silver',
      name: 'Porsche 993 Classic Silverline',
      category: 'Classic Cars',
      categorySlug: '993',
      price: 1_500_000_000,
      stock: 3,
      imageUrl: '/assets/images/mobil6.jpg',
      description: 'Porsche 993 Classic Silverline, simbol keanggunan abadi dengan sentuhan warna perak.',
    },
    {
      id: 'classic-993-green',
      slug: 'classic-porsche-993-green',
      name: 'Porsche 993 Heritage Green',
      category: 'Classic Cars',
      categorySlug: '993',
      price: 1_800_000_000,
      stock: 0,
      imageUrl: '/assets/images/mobil7.jpg',
      description: 'Porsche 993 Heritage Green, pilihan klasik nan langka untuk kolektor sejati.',
    },
    {
      id: 'classic-993-lightblue',
      slug: 'classic-porsche-993-lightblue',
      name: 'Porsche 993 Vintage Sky Blue',
      category: 'Classic Cars',
      categorySlug: '993',
      price: 2_000_000_000,
      stock: 1,
      imageUrl: '/assets/images/mobil8.jpg',
      description: 'Porsche 993 Vintage Sky Blue, perpaduan antara pesona vintage dan warna biru cerah yang memikat.',
    }
  ];
}
